#!/usr/bin/env python3
"""V189 -> V190: restore native moving-elevator pathfinding/rider transport. Exact-blob gated."""
from pathlib import Path
import hashlib,sys
BASE={"lite":"6acb643ee40954a53f2e71c86caea10969e986f8","full":"e778ce5baa7f39f7dcb7a229961089e9c1ea2632"}
TARGET={"lite":"10601a1deb58462ab96f222dd7e152ee51dbaca2","full":"348c5186362c94ebe4bef923c15a27be5e4300dc"}
def blob(b): return hashlib.sha1(b"blob "+str(len(b)).encode()+b"\0"+b).hexdigest()
def between(t,a,b,new):
 i=t.index(a);j=t.index(b,i);return t[:i]+new+t[j:]
def once(t,a,b):
 if t.count(a)!=1: raise ValueError(f"gate {a[:70]!r}: {t.count(a)}")
 return t.replace(a,b,1)
HELPER=' function effectiveElevatorTileAt(x,y,z){\n   // lm_win.exe 0x441f53..0x441f6c and 0x4420a6..0x4420bf: visible 124 is the moving platform; path/height logic reads its hidden under-tile from cell byte +1.\n   const key=vk(x,y,z),t=tileAt(x,y,z);return t===124&&elevatorUnderlay.has(key)?elevatorUnderlay.get(key):t;\n }\n function elevatorVerticalModeForTile(t){return t===120?1:t===121?-1:0}\n function isElevatorShaftTile(t){return t>=120&&t<=124}\n'
PREPARE=' function prepareInitialElevators(){\n   // lm_win.exe 0x4071ca..0x407363: raw tile 120 allocates one of four lift records, keeps 120 in hidden byte +1 and exposes moving platform tile 124.\n   elevatorUnderlay.clear();elevators=[];\n   const starts=vox.filter(q=>q.v===120).slice().sort((a,b)=>a.z-b.z||(a.y*32+a.x)-(b.y*32+b.x)).slice(0,4);\n   for(const q of starts){const key=vk(q.x,q.y,q.z);elevatorUnderlay.set(key,120);q.v=124;elevators.push({x:q.x,y:q.y,z:q.z,dir:1,pause:0,active:true})}\n }\n'
BACKAI=" function originalCardinalBacktrack(start,end,dist){\n   // lm_win.exe 0x4424e0..0x4428da: rebuild from target using elevator vertical predecessors first, then CARD 0,2,4,6; only a strictly lower distance replaces the chosen predecessor.\n   const out=[];let cur=end;\n   while(cur!==start){const [x,y,z]=cur.split(',').map(Number),curDist=dist.get(cur);if(curDist==null)return null;let prev=null,marker=-1,best=curDist;\n     const considerVertical=(pz,m)=>{if(pz<0||pz>=48)return;const k=vk(x,y,pz),nd=dist.get(k);if(nd!=null&&nd<best){best=nd;prev=k;marker=m}};\n     const t=effectiveElevatorTileAt(x,y,z),shaftInterior=(t===122||t===123||t===124);if(t===120)considerVertical(z+1,0xff);else if(t===121)considerVertical(z-1,0xfe);else if(shaftInterior){considerVertical(z+1,0xff);considerVertical(z-1,0xfe)}\n     // lm_win.exe 0x4427f6: 122/123/124 jump straight to predecessor commit after vertical probes; only endpoints/non-shaft cells continue into the 0,2,4,6 horizontal loop at 0x4427fb.\n     if(!shaftInterior)for(const d of CARD){const [dx,dy]=DIRS[d],nx=x+dx,ny=y+dy,nz=resolveStep(nx,ny,z,x,y);if(nz==null)continue;const k=vk(nx,ny,nz),nd=dist.get(k);if(nd!=null&&nd<best){best=nd;prev=k;marker=(d+4)&7}}\n     if(prev==null)return null;out.push({x,y,z,dir:marker});cur=prev;\n   }\n   out.reverse();return out;\n }\n function routeWithOriginalAiBlocks(u,tx,ty,blocked,targetZ=null){\n   const sx=Math.floor(u.x),sy=Math.floor(u.y),sz=Math.round(u.z),gx=Math.floor(tx),gy=Math.floor(ty),start=vk(sx,sy,sz),q=[[sx,sy,sz,0]],dist=new Map([[start,0]]);let end=null,head=0;\n   blocked=blocked||new Set();const gz=targetZ==null?null:Math.round(targetZ);\n   while(head<q.length&&q.length<45000){const [x,y,z,verticalMode]=q[head++],base=vk(x,y,z),d0=dist.get(base)||0;if(x===gx&&y===gy&&(gz===null||z===gz)){end=base;break}\n     if(verticalMode){const nz=z+verticalMode;if(nz>=0&&nz<48){const t=effectiveElevatorTileAt(x,y,nz),k=vk(x,y,nz);if(isElevatorShaftTile(t)&&!commanderBlocksRoute(u,x,y,nz)&&!blocked.has(k)&&!dist.has(k)){dist.set(k,d0+1);q.push([x,y,nz,verticalMode>0?(t===121?0:1):(t===120?0:-1)])}}continue}\n     for(const d of CARD){const [dx,dy]=DIRS[d],nx=x+dx,ny=y+dy,nz=resolveStep(nx,ny,z,gx,gy);if(nz==null)continue;if(commanderBlocksRoute(u,nx,ny,nz))continue;const k=vk(nx,ny,nz);if(blocked.has(k)||dist.has(k))continue;dist.set(k,d0+1);q.push([nx,ny,nz,elevatorVerticalModeForTile(effectiveElevatorTileAt(nx,ny,nz))])}}\n   return end?originalCardinalBacktrack(start,end,dist):null;\n }\n"
REACH=' function buildOriginalReachMap(u,radius,blocked){\n   // lm_win.exe 0x43ef84..0x43f5c9: 120 seeds upward propagation, 121 downward propagation, and 122/123 continue that same vertical queue state until the opposite endpoint.\n   const sx=Math.floor(u.x),sy=Math.floor(u.y),sz=Math.round(u.z),start=vk(sx,sy,sz),q=[[sx,sy,sz,0]],prev=new Map([[start,null]]),how=new Map(),dist=new Map([[start,0]]);let head=0;\n   blocked=blocked||new Set();radius=Math.max(0,Math.min(255,Math.trunc(radius==null?255:radius)));\n   while(head<q.length&&q.length<45000){const [x,y,z,verticalMode]=q[head++],base=vk(x,y,z),d0=dist.get(base)||0;if(d0>=radius)continue;\n     if(verticalMode){const nz=z+verticalMode;if(nz>=0&&nz<48){const t=effectiveElevatorTileAt(x,y,nz),k=vk(x,y,nz);if(isElevatorShaftTile(t)&&!commanderBlocksRoute(u,x,y,nz)&&!blocked.has(k)&&!prev.has(k)){prev.set(k,base);how.set(k,verticalMode>0?0xfe:0xff);dist.set(k,d0+1);q.push([x,y,nz,verticalMode>0?(t===121?0:1):(t===120?0:-1)])}}continue}\n     for(const dir of CARD){const [dx,dy]=DIRS[dir],nx=x+dx,ny=y+dy,nz=resolveStep(nx,ny,z,nx,ny);if(nz==null)continue;if(commanderBlocksRoute(u,nx,ny,nz))continue;const k=vk(nx,ny,nz);if(blocked.has(k)||prev.has(k))continue;prev.set(k,base);how.set(k,dir);dist.set(k,d0+1);q.push([nx,ny,nz,elevatorVerticalModeForTile(effectiveElevatorTileAt(nx,ny,nz))])}}\n   return{start,prev,how,dist};\n }\n'
RESOLVE=' function resolveStep(x,y,z,goalX,goalY){\n   if(x<0||y<0||x>=32||y>=32)return null;z=Math.round(z);\n   // lm_win.exe 0x441e80: inspect the target column from current Z through Z+3 first. Visible 124 is replaced by its hidden under-tile before all property tests.\n   let blockedSeen=false;\n   for(let dz=0;dz<=3;dz++){\n     const zz=z+dz;if(zz<0||zz>=48)break;const visible=tileAt(x,y,zz);if(!visible)continue;blockedSeen=true;const t=effectiveElevatorTileAt(x,y,zz);\n     if(t===120||t===121)return zz;\n     const flags=originalTileFlags(t);\n     if(flags&0x0004)return null;\n     if(visible===124?(flags&0x0080)!==0:runtimeWalkSurfaceAt(x,y,zz))return zz;\n     if(flags&0x0100)blockedSeen=false;\n   }\n   if(blockedSeen)return null;\n   for(let dd=1;dd<=2;dd++){\n     const zz=z-dd;if(zz<0)break;const visible=tileAt(x,y,zz);if(!visible)continue;const t=effectiveElevatorTileAt(x,y,zz);\n     if(t===120||t===121)return zz;\n     const flags=originalTileFlags(t);\n     if(dd===1&&(flags&0x0004))return null;\n     if(visible===124?(flags&0x0080)!==0:runtimeWalkSurfaceAt(x,y,zz))return zz;\n   }\n   return null;\n }\n'
ROUTE=' function route(u,tx,ty,targetZ=null){\n   const sx=Math.floor(u.x),sy=Math.floor(u.y),sz=Math.round(u.z),gx=Math.floor(tx),gy=Math.floor(ty),gz=targetZ==null?null:Math.round(targetZ),start=vk(sx,sy,sz),q=[[sx,sy,sz,0]],dist=new Map([[start,0]]);let end=null,head=0;\n   while(head<q.length&&q.length<45000){const [x,y,z,verticalMode]=q[head++],base=vk(x,y,z),d0=dist.get(base)||0;if(x===gx&&y===gy&&(gz===null||z===gz)){end=base;break}\n     if(verticalMode){const nz=z+verticalMode;if(nz>=0&&nz<48){const t=effectiveElevatorTileAt(x,y,nz),k=vk(x,y,nz);if(isElevatorShaftTile(t)&&!commanderBlocksRoute(u,x,y,nz)&&!dist.has(k)){dist.set(k,d0+1);q.push([x,y,nz,verticalMode>0?(t===121?0:1):(t===120?0:-1)])}}continue}\n     for(const d of CARD){const [dx,dy]=DIRS[d],nx=x+dx,ny=y+dy,nz=resolveStep(nx,ny,z,gx,gy);if(nz==null)continue;\n       if(commanderBlocksRoute(u,nx,ny,nz))continue;const k=vk(nx,ny,nz);if(dist.has(k))continue;dist.set(k,d0+1);q.push([nx,ny,nz,elevatorVerticalModeForTile(effectiveElevatorTileAt(nx,ny,nz))])}}\n   return end?originalCardinalBacktrack(start,end,dist):null;\n }\n'
CACHED=" function cachedPathNodeValid(u,p){\n   if(!u||!p)return false;\n   const cx=Math.floor(u.x),cy=Math.floor(u.y),cz=Math.round(u.z),dx=p.x-cx,dy=p.y-cy;\n   if(p.dir===0xfe||p.dir===0xff){const dz=p.dir===0xfe?1:-1,t=effectiveElevatorTileAt(p.x,p.y,p.z);return p.x===cx&&p.y===cy&&p.z===cz+dz&&isElevatorShaftTile(t)&&!commanderBlocksRoute(u,p.x,p.y,p.z)}\n   const nz=resolveStep(p.x,p.y,cz,p.x,p.y);if(nz==null||nz!==p.z||commanderBlocksRoute(u,p.x,p.y,nz))return false;\n   if(dx&&dy){\n     if(resolveStep(cx+dx,cy,cz,cx+dx,cy)==null||resolveStep(cx,cy+dy,cz,cx,cy+dy)==null)return false;\n   }\n   return true;\n }\n // Failed route results are valid until the unit, destination, or map topology changes.\n // Retrying an identical full-map BFS on each animation tick does not change the result;\n // it only freezes large maps when a manual destination becomes isolated by construction.\n function getOriginalUnitPassSlots(peekOnly=false){\n   // lm_win.exe 0x43a035..0x43a085: each processor invocation visits 63 entries while the 0..63 slot cursor keeps rotating.\n   // This means exactly one slot is omitted per pass, and the omitted slot changes on the next pass.\n   const slots=[];let c=unitPassCursor&63;for(let n=0;n<63;n++){slots.push(c);c=(c+1)&63}if(!peekOnly)unitPassCursor=c;return slots;\n }\n function pendingRouteKey(u){\n   if(!u||!u.target)return null;\n   const t=u.target;\n   return [worldWalkabilityVersion,Math.floor(u.x),Math.floor(u.y),Math.round(u.z),\n     Math.floor(t.x),Math.floor(t.y),t.z==null?'*':Math.round(t.z),\n     t.slot==null?'*':t.slot].join('|');\n }\n function resolvePendingRoute(u){\n   if(!u||!u.target)return null;\n   const key=pendingRouteKey(u);\n   if(u.failedRouteKey===key)return null;\n   const p=route(u,u.target.x,u.target.y,u.target.z);\n   // An empty route is a legitimate result for a unit already on its destination;\n   // retain it, just as the old update loop did, rather than treating it as failure.\n   u.path=p;u.pathPos=0;u.failedRouteKey=p===null?key:null;\n   return p;\n }\n"
ELEVTICK=" function finishPathArrival(u){\n   u.path=null;u.elevatorRide=false;\n   if(u.manualOrder==='standby'){u.target=null;u.actionCode=0;u.state=0;u.unitWord=((u.unitWord||0)&0xff00);u.actionTarget=null}\n   else if(u.manualOrder==='autoAfterMove'){u.target=null;u.actionCode=1;u.state=1;u.unitWord=((u.unitWord||0)&0xff00)|1;u.actionTarget=null;u.manualOrder=null;u.aiScan=0}\n   else if(u.actionCode===4&&u.actionTarget){u.target=null}\n   else if((u.actionCode===5||u.actionCode===6||u.actionCode===8||u.actionCode===9||u.actionCode===10||u.actionCode===11||u.actionCode===12||u.actionCode===13||u.actionCode===14||u.actionCode===16)&&u.actionTarget){u.target=null}\n   else if(u.f===4&&u.actionCode===15){u.target=null;u.path=null;u.neutralStep=false}\n   else if(u.actionCode!==2&&u.actionCode!==3){u.target=null;u.actionCode=1;if(u.f===4){u.unitWord=0x1001;u.state=1}u.actionTarget=null}\n }\n function tickOriginalElevators(){\n   // lm_win.exe 0x43b116..0x43b7c6: four lift records move visible tile 124 one Z level per pass between hidden 120/121 endpoints, pausing 30 passes at each reversal.\n   for(const e of elevators){if(!e.active)continue;if(e.pause>0){e.pause--;continue}const oldZ=e.z,oldKey=vk(e.x,e.y,oldZ),under=elevatorUnderlay.get(oldKey)??effectiveElevatorTileAt(e.x,e.y,oldZ);\n     if(e.dir>0&&under===121){e.dir=-1;e.pause=30;continue}if(e.dir<0&&under===120){e.dir=1;e.pause=30;continue}\n     const nz=oldZ+e.dir;if(nz<0||nz>=48)continue;const targetVisible=tileAt(e.x,e.y,nz),targetUnder=effectiveElevatorTileAt(e.x,e.y,nz);if(!isElevatorShaftTile(targetUnder)||targetVisible===124)continue;\n     let rider=units.find(u=>u&&u.alive&&u.elevatorRide&&Math.floor(u.x)===e.x&&Math.floor(u.y)===e.y&&Math.round(u.z)===oldZ)||null;\n     if(rider){const contacted=stepCellContact(rider,{x:e.x,y:e.y,z:nz});if(contacted){if(contacted.f===rider.f){if(!mergeFriendlyPair(rider,contacted)||!rider.alive)continue}else{exchange(rider,contacted);if(!rider.alive)rider.elevatorRide=false;continue}}}\n     elevatorUnderlay.delete(oldKey);setWorldTile(e.x,e.y,oldZ,under,0);setWorldTile(e.x,e.y,nz,124,0);elevatorUnderlay.set(vk(e.x,e.y,nz),targetUnder);e.z=nz;\n     if(rider&&rider.alive){rider.z=nz;const p=rider.path&&rider.path[rider.pathPos];if(p&&(p.dir===0xfe||p.dir===0xff)&&p.x===e.x&&p.y===e.y&&p.z===nz)rider.pathPos++;if(rider.path&&rider.pathPos>=rider.path.length)finishPathArrival(rider)}\n   }\n }\n"

def upgrade(raw,full=False):
 exp=BASE["full" if full else "lite"];got=blob(raw)
 if got!=exp: raise ValueError(f"Unknown V189 blob expected {exp} got {got}")
 t=raw.decode("utf8")
 t=once(t,"territoryUnderlay=new Map(),deathVisuals=[]","territoryUnderlay=new Map(),elevatorUnderlay=new Map(),elevators=[],deathVisuals=[]")
 t=between(t," function effectiveElevatorTileAt(" if " function effectiveElevatorTileAt(" in t else " function refreshSurfaceCell("," function refreshSurfaceCell(",HELPER) if " function effectiveElevatorTileAt(" in t else t.replace(" function refreshSurfaceCell(",HELPER+" function refreshSurfaceCell(",1)
 t=t.replace(" function initialPowerForTile(",PREPARE+" function initialPowerForTile(",1)
 t=between(t," function originalCardinalBacktrack("," function trackedUnitRouteWithOriginalAiBlocks(",BACKAI)
 t=between(t," function buildOriginalReachMap("," function originalReachCandidate(",REACH)
 t=between(t," function resolveStep("," function route(u,tx,ty,targetZ=null){",RESOLVE)
 t=between(t," function route(u,tx,ty,targetZ=null){"," function localEnemy(",ROUTE)
 t=between(t," function cachedPathNodeValid("," function refreshCachedPath(",CACHED)
 t=t.replace(" update=function(dt){",ELEVTICK+" update=function(dt){",1)
 t=once(t,"if(paused||ended)return;ticks+=dt;processWorldScan(dt);","if(paused||ended)return;tickOriginalElevators();ticks+=dt;processWorldScan(dt);")
 t=once(t,"if(u.path&&u.pathPos<u.path.length){if(!refreshCachedPath(u))continue;const p=u.path&&u.path[u.pathPos];if(!p)continue;const contacted=stepCellContact(u,{x:p.x,y:p.y,z:p.z});if(contacted){","if(u.path&&u.pathPos<u.path.length){if(!refreshCachedPath(u))continue;const p=u.path&&u.path[u.pathPos];if(!p)continue;\n       if(p.dir===0xfe||p.dir===0xff){const e=elevators.find(v=>v.active&&v.x===Math.floor(u.x)&&v.y===Math.floor(u.y)&&v.z===Math.round(u.z)&&tileAt(v.x,v.y,v.z)===124);if(!e){u.elevatorRide=false;continue}u.elevatorRide=true;continue}\n       u.elevatorRide=false;const contacted=stepCellContact(u,{x:p.x,y:p.y,z:p.z});if(contacted){")
 a=t.index("}const tx=p.x+.5,ty=p.y+.5,dx=tx-u.x,dy=ty-u.y,d=Math.hypot(dx,dy);u.dir=p.dir;if(d<.08){")
 e="}else{const step=Math.min(d,.028*dt)";b=t.index(e,a)
 t=t[:a]+"}const tx=p.x+.5,ty=p.y+.5,dx=tx-u.x,dy=ty-u.y,d=Math.hypot(dx,dy);u.dir=p.dir;if(d<.08){u.x=tx;u.y=ty;u.z=p.z;u.pathPos++;if(u.pathPos>=u.path.length)finishPathArrival(u)"+t[b:]
 t=once(t,"prepareInitialTerritoryOverlays();rebuildSurface();rebuildVoxel();initCellPower();","prepareInitialTerritoryOverlays();prepareInitialElevators();rebuildSurface();rebuildVoxel();initCellPower();")
 t=once(t,"getTerritoryUnderlay:(x,y,z)=>territoryUnderlay.get(vk(x,y,z)),route,resolveStep,","getTerritoryUnderlay:(x,y,z)=>territoryUnderlay.get(vk(x,y,z)),getElevatorUnderlay:(x,y,z)=>elevatorUnderlay.get(vk(x,y,z)),getElevators:()=>elevators.map(e=>({...e})),prepareInitialElevators,tickOriginalElevators,effectiveElevatorTileAt,route,resolveStep,")
 for a,b,c in [("Original Restoration V189","Original Restoration V190",3),("ORIGINAL RULE RESTORATION · V189","ORIGINAL RULE RESTORATION · V190",1),("モナークモナーク · v189","モナークモナーク · v190",1)]:
  if t.count(a)!=c: raise ValueError((a,t.count(a)))
  t=t.replace(a,b)
 out=t.encode();target=TARGET["full" if full else "lite"]
 if blob(out)!=target: raise ValueError(f"V190 target mismatch {blob(out)} != {target}")
 return out
def main():
 if sys.argv[1:2]==["--full"] and len(sys.argv)==4:
  src,dst=map(Path,sys.argv[2:]);dst.write_bytes(upgrade(src.read_bytes(),True))
 elif len(sys.argv)==3:
  src,dst=map(Path,sys.argv[1:]);dst.write_bytes(upgrade(src.read_bytes(),False))
 elif len(sys.argv)==1:
  p=Path("index.html");raw=p.read_bytes();got=blob(raw)
  if got==BASE["lite"]: out=upgrade(raw);p.write_bytes(out);Path("monarch_v190_lite.html").write_bytes(out)
  elif got==TARGET["lite"]: Path("monarch_v190_lite.html").write_bytes(raw)
  else: raise ValueError(f"Unknown index blob {got}")
  print("PASS V190",blob(p.read_bytes()))
 else: raise SystemExit("usage: upgrade_v190.py [V189 V190] | [--full V189 V190]")
if __name__=="__main__": main()
